### PR TITLE
WIP: Added info for Kobe. Yippee!!

### LINKED ISSUE #2: Kobe add info
Add your name, email, and phone number

### PR DESCRIPTION
**Pull request by kcouv**
WIP: 

Closes #2 

I have added my JSON object.

There still needs to be a comma added at the end of Spencer's JSON object.

### CODE REVIEW

**Comment by SebastianNeiswanger** [comment]
Yipee!

**Comment by kcouv** [comment]
Actually it's done

**Review by SebastianNeiswanger — CHANGES_REQUESTED** [review]
no

**Review by SebastianNeiswanger — APPROVED** [review]
wow grreatjw jbb-o jdwoj akfg

**Pull request merged**
